[package]
name = "yamos6502e"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yamos6502e"
path = "src/bin/main.rs"

[dependencies]
yamos6502 = { path = "src/lib"}

clap = { version = "4.1", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
anyhow = "1"
